
- name: test 1
  shell: |
     sudo apt update
     sudo apt install -y docker.io apt-get
     sudo systemctl enable docker.service --now
     swapoff -a
     echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf
     echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
     sudo sysctl -p
     sudo apt install -y apt-transport-https curl
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
     sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
     curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -



- name: add repo
  copy:
     dest: /etc/yum.repos.d/kubernetes.repo
     content: |
	      deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: test 2
  shell: |
     sudo apt-get update
     sudo apt-get install -y docker-ce=5:20.10.7~3-0~ubuntu-$(lsb_release -cs) kubelet=1.21.1-00 kubeadm=1.21.1-00 kubectl=1.21.1-00
     sudo apt-mark hold docker-ce kubelet kubeadm kubectl
     swapoff -a
     sudo kubeadm init
     mkdir -p $HOME/.kube
     sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config
